# src/hyperstat/backtest/reports.py
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional

import pandas as pd

from .metrics import PerformanceMetrics


@dataclass(frozen=True)
class BacktestReport:
    equity_curve: pd.DataFrame        # index ts, col equity
    pnl_curve: pd.DataFrame           # index ts, cols: pnl_price, pnl_funding, costs, pnl_net_step
    turnover: pd.Series              # index ts, sum(abs(delta_w))
    weights: pd.DataFrame            # index ts, columns symbols
    metrics: PerformanceMetrics
    breakdown: Dict[str, float]
    meta: Dict[str, str]


def _ensure_dir(p: Path) -> None:
    p.mkdir(parents=True, exist_ok=True)


def save_report_csv(report: BacktestReport, out_dir: str) -> None:
    p = Path(out_dir)
    _ensure_dir(p)

    report.equity_curve.to_csv(p / "equity_curve.csv")
    report.pnl_curve.to_csv(p / "pnl_curve.csv")
    report.turnover.to_frame("turnover").to_csv(p / "turnover.csv")
    report.weights.to_csv(p / "weights.csv")

    # metrics + breakdown
    m = pd.DataFrame([report.metrics.__dict__]).T
    m.columns = ["value"]
    m.to_csv(p / "metrics.csv")

    b = pd.DataFrame([report.breakdown]).T
    b.columns = ["value"]
    b.to_csv(p / "breakdown.csv")


def save_report_html(report: BacktestReport, out_dir: str, title: str = "hyperstat backtest") -> None:
    p = Path(out_dir)
    _ensure_dir(p)

    metrics_df = pd.DataFrame([report.metrics.__dict__]).T
    metrics_df.columns = ["value"]

    breakdown_df = pd.DataFrame([report.breakdown]).T
    breakdown_df.columns = ["value"]

    meta_df = pd.DataFrame([report.meta]).T
    meta_df.columns = ["value"]

    html = f"""
    <html>
      <head>
        <meta charset="utf-8"/>
        <title>{title}</title>
        <style>
          body {{ font-family: Arial, sans-serif; margin: 24px; }}
          h1 {{ margin-bottom: 8px; }}
          .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 18px; }}
          .card {{ border: 1px solid #ddd; border-radius: 10px; padding: 14px; }}
          table {{ border-collapse: collapse; width: 100%; }}
          th, td {{ border: 1px solid #eee; padding: 6px 8px; text-align: left; }}
          th {{ background: #fafafa; }}
          .small {{ color: #666; font-size: 12px; }}
        </style>
      </head>
      <body>
        <h1>{title}</h1>
        <div class="small">Generated by hyperstat</div>

        <div class="grid" style="margin-top:16px;">
          <div class="card">
            <h2>Metrics</h2>
            {metrics_df.to_html(header=False)}
          </div>
          <div class="card">
            <h2>Breakdown</h2>
            {breakdown_df.to_html(header=False)}
          </div>
        </div>

        <div class="card" style="margin-top:18px;">
          <h2>Meta</h2>
          {meta_df.to_html(header=False)}
        </div>

        <div class="card" style="margin-top:18px;">
          <h2>Equity curve (head)</h2>
          {report.equity_curve.head(25).to_html()}
        </div>

        <div class="card" style="margin-top:18px;">
          <h2>Equity curve (tail)</h2>
          {report.equity_curve.tail(25).to_html()}
        </div>
      </body>
    </html>
    """
    (p / "report.html").write_text(html, encoding="utf-8")
